src/Hybrid/time_triggered.jl
=> solve_hybrid: positional alguments to keyword

src/Hybrid/time_triggered.jl
=> remove type annotation of X0

src/Algorithms/TMJets/post.jl, src/Flowpipes/fields.jl, src/Initialization/init_DifferentialEquations.jl, test/algorithms/TMJets.jl, test/models/linear/exponential1D.jl, test/models/nonlinear/vanderpol.jl, test/runtests.jl
=> #79 - Update IVPs interface for TMJets

src/Algorithms/BOX/reach.jl, src/Algorithms/GLGM06/reach.jl, src/Flowpipes/flowpipes.jl, src/Flowpipes/reachsets.jl, src/Flowpipes/setops.jl, src/Flowpipes/solutions.jl, test/runtests.jl, test/solve.jl
- Fix some projection methods + add tests.
- Use `Zonotope` constructor flag.
- Merge GLGM06 method for "static" case.
- Fix BOX to use the recurrence version (no wrapping).
=> Various fixes

src/Algorithms/ASB07/post.jl, src/Algorithms/GLGM06/post.jl, src/Continuous/discretization.jl, src/Flowpipes/setops.jl, src/Hybrid/time_triggered.jl
- use internal overapproximation / linear map functions
- handling Omega0 and Phi as in GLGM06
=> various updates in ASB07

test/algorithms/BOX.jl, test/algorithms/GLGM06.jl, test/solve.jl
=> Add tests for dimension

src/Continuous/solve.jl, test/solve.jl
=> Update solve tests + tspan duck typing

src/Algorithms/ASB07/ASB07.jl, src/Algorithms/ASB07/post.jl, src/Algorithms/BFFPSV18/BFFPSV18.jl, src/Algorithms/BOX/BOX.jl, src/Algorithms/BOX/post.jl, src/Algorithms/GLGM06/GLGM06.jl, src/Algorithms/GLGM06/post.jl, src/Algorithms/INT/INT.jl, src/Algorithms/LGG09/LGG09.jl, src/Algorithms/LGG09/post.jl, src/Algorithms/TMJets/TMJets.jl, src/Continuous/solve.jl, src/Initialization/exports.jl, test/algorithms/TMJets.jl, test/runtests.jl
=> rsetrep to retrieve reach set rep for an algorithm

src/Algorithms/ASB07/reach.jl, src/Flowpipes/setops.jl
Closes #120.
---
reference notebook: https://github.com/mforets/escritoire/blob/master/2020/Week16/OrderReductionMethods.ipynb
=> revised order reduction methods

src/Initialization/exports.jl
adds Convexify to exports.jl (# Lazy operations).
=> adds Convexify to exports.jl

src/Algorithms/BFFPSV18/BFFPSV18.jl, src/Algorithms/LGG09/LGG09.jl, test/algorithms/LGG09.jl
=> #206 - Duck typing LGG09 options

src/Flowpipes/flowpipes.jl
Added one function
Closes #229.
=> issue #229 - Generalize convexify function for SparseReachSet

src/Algorithms/BFFPSV18/reach_inhomog.jl
Add intersection w/invariant for BFFPSV18 and dense matrix operations.
=> issue #225 for dense matrix ops

src/Algorithms/TMJets/post.jl, src/Flowpipes/reachsets.jl
See #199.
Joint with @SebastianGuadalupe.
=> Add conversion from hyperrectangular / zonotopic sets to TMReachSets

src/Algorithms/TMJets/post.jl
joint with @SebastianGuadalupe
=> fix TMJets when the first reach-set is empty

src/Hybrid/solve.jl
=> #264 - Add warning if max_jumps is reached

src/Flowpipes/flowpipes.jl, src/Flowpipes/solutions.jl, test/algorithms/ASB07.jl, test/algorithms/GLGM06.jl, test/algorithms/TMJets.jl
Closes #316
Generalizes shift function for flowpipes of AbstractReachSets.
=> Issue #316

src/Hybrid/solve.jl
=> fixpoint_check added to hybrid solve

src/Algorithms/QINT/QINT.jl, src/Algorithms/QINT/post.jl, src/Algorithms/QINT/reach_homog.jl, src/Initialization/exports.jl, src/ReachabilityAnalysis.jl, test/algorithms/QINT.jl, test/runtests.jl
ref notebook: https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/2020/Week40/ScalarQuadraticSolver.ipynb
=> Add QINT method for scalar quadratic ODEs

src/Algorithms/LGG09/post.jl, src/Algorithms/LGG09/reach_homog.jl, src/Algorithms/LGG09/reach_inhomog.jl, src/Flowpipes/reachsets.jl
Multithreading for LGG09 in the loops over CustomDirections
=> LGG09 with multithreading

src/Flowpipes/setops.jl
=> #374 - Cleanup vertices of CHA

test/algorithms/INT.jl
=> Test for affine ODE

src/Flowpipes/reachsets.jl, src/Initialization/init.jl, test/reachsets.jl
Closes https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/254.
=> Update and test conversion of TM reachsets

test/models/burgers.jl, test/runtests.jl, test/solve.jl
Add 1D Burgers equation test.
PDE spatial discratization follows Eq. (6.4) from this [reference](https://arxiv.org/abs/2011.03185).
=> 1D Burgers equation test

src/Flowpipes/reachsets.jl
test with
```julia
prob, tspan = vanderpol()
sol = solve(prob, tspan=tspan);
R = sol[10]
A = set(overapproximate(R, Zonotope, tstart(R)))
B = set(overapproximate(R, Zonotope, tend(R)))
C = set(overapproximate(R, Zonotope))
plot(C, lab="tspan(R)")
plot!(A, lab="tstart(R)")
plot!(B,lab="tend(R)")
```
=> add zonotope oa of TMReachsets with a time point

src/Algorithms/TMJets/TMJets.jl, src/Algorithms/TMJets/post.jl, src/Algorithms/TMJets/reach.jl
=> #199 - Changes to accept an initial TM in TMJets algorithm

src/ReachSets/TaylorModelReachSet.jl
=> WIP - Add overapproximation of TM with zonotope by mincing in space

docs/generate.jl, docs/make.jl, examples/SquareWaveOscillator/SquareWaveOscillator.jl, src/Flowpipes/HybridFlowpipe.jl
- fix hybrid flowpipe evaluation for time intervals
- add square wave oscillator example
=> fix hybrid flowpipe evaluation for time intervals

src/Flowpipes/recipes.jl
=> #462 - Plotting of flowpipes merges segments

src/Algorithms/TMJets/reach.jl
cf https://github.com/JuliaIntervals/TaylorModels.jl/pull/110
=> fix in TMJets

src/Algorithms/TMJets/post.jl
There should probably be a test for this method :wink:
=> Fix variable name

src/Algorithms/BFFPSV18/reach_homog.jl
`N` was undefined in this method.
=> Fix undefined-variable error

src/Algorithms/TMJets/common.jl, src/ReachSets/TaylorModelReachSet.jl
Requires https://github.com/JuliaReach/LazySets.jl/pull/2727.
=> add option to remove generators

src/Flowpipes/setops.jl
=> #502 - Pass backend to FallBackIntersection

src/Flowpipes/MixedFlowpipe.jl
Note that the implementation returns a `Flowpipe`.
=> linear_map/affine_map for MixedFlowpipe

src/Flowpipes/Flowpipe.jl, src/Flowpipes/MixedFlowpipe.jl
=> Fix linear_map/affine_map of MixedFlowpipe

Project.toml, src/Initialization/init.jl
=> use common solve

.github/workflows/docs.yml, docs/src/man/hybrid.md, docs/src/man/linear.md, docs/src/man/nonlinear.md, src/Discretization/discretization.jl, src/Initialization/init.jl
=> init fix, update some docs

src/Discretization/FirstOrderZonotope.jl, src/Discretization/FirstOrderddt.jl, src/Discretization/discretization.jl, src/Initialization/exports.jl, test/algorithms/LGG09.jl
=> Update discretization methods names

src/Flowpipes/setops.jl, src/ReachSets/TaylorModelReachSet.jl, test/reachsets.jl
Closes https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/613
=> Subdomain overapproximation of TM using zonotopes

Project.toml, src/Algorithms/CARLIN/CARLIN.jl, src/Algorithms/CARLIN/kronecker.jl, src/Algorithms/CARLIN/post.jl, src/Algorithms/CARLIN/reach.jl, src/Initialization/exports.jl, test/algorithms/CARLIN.jl, test/runtests.jl
See the test for a simple use case.
---
Main things to be done as follow-up work are:
- ~~Incorporate the `compressed` option~~
- Extend `canonical_form` to handle a general vector field
=> Add initial version of the CARLIN algorithm

src/Discretization/Backward.jl, src/Discretization/CorrectionHull.jl, src/Discretization/FirstOrder.jl, src/Discretization/FirstOrderZonotope.jl, src/Discretization/Forward.jl, src/Discretization/ForwardBackward.jl, src/Discretization/NoBloating.jl, src/Discretization/SecondOrderddt.jl, src/Discretization/StepIntersect.jl
Some line breaks were missing.
=> Consistent printing of discretization structs

src/ReachSets/TaylorModelReachSet.jl, test/reachsets.jl
=> #654 - Fix zonotope->TM conversion for low order

examples/Quadrotor/Quadrotor.jl
=> #669 - Add references for quadrotor example

src/Initialization/init_DifferentialEquations.jl
Other minor changes:
- reduce the default number of simulations to 10 (faster)
- rename variable for consistency
=> Pass simulation kwargs in distributed setting

src/Flowpipes/setops.jl, src/Initialization/init_DifferentialEquations.jl
=> #716 #718 - Fix convert_or_overapproximate and concretize

Project.toml, test/Project.toml
Closes #700.
Closes #712.
Closes #723.
Closes #724.
=> Freeze package compat

Project.toml
=> Support for IntervalMatrices v0.9

examples/LotkaVolterraTangential/LotkaVolterraTangential, examples/Quadrotor/Quadrotor.jl, test/models/generated/Quadrotor.jl
=> #757 - Fix invalid comments in examples

src/Algorithms/BFFPSV18/reach_homog.jl, src/Algorithms/BFFPSV18/reach_inhomog.jl, src/Flowpipes/setops.jl, src/ReachSets/AbstractLazyReachSet.jl, src/ReachSets/AbstractReachSet.jl, src/ReachSets/TaylorModelReachSet.jl
This is the first two commits of #801 to move forward.
=> Fix ambiguities

src/Continuous/normalization.jl, src/Flowpipes/MappedFlowpipe.jl, src/Flowpipes/setops.jl
=> Fix some piracies

src/Algorithms/TMJets/common.jl
This function was a leftover from the removal of `TMJets20` in #819.
=> Remove old helper function

src/Continuous/solve.jl, src/Flowpipes/clustering.jl, src/Hybrid/solve.jl, src/ReachSets/AbstractLazyReachSet.jl, src/ReachSets/AbstractReachSet.jl, src/ReachSets/TaylorModelReachSet.jl
The build error (coverage upload) is unrelated.
=> Simplify code for UnionSet and UnionSetArray

Project.toml
=> Allow CarlemanLinearization v0.4

src/Algorithms/GLGM06/GLGM06.jl
The argument was just ignored.
=> Use `preallocate` argument in `GLGM06`

docs/Project.toml
=> Allow JLD2 v0.5

Project.toml, docs/Project.toml, test/Project.toml
Closes #877.
Closes #878.
Closes #879.
=> Bump LazySets v3

src/Discretization/FirstOrderModule.jl, src/Discretization/FirstOrderZonotopeModule.jl
=> #900 - Fix FirstOrder and FirstOrderZonotope with zero matrix

src/Discretization/FirstOrderModule.jl, src/Discretization/ForwardModule.jl
See #903.
This branch is based on #904.
=> #903 - Fix/add `setops` option for `Forward`/`FirstOrder`

Project.toml, src/Initialization/init.jl
The use case was removed in #544.
=> Remove redundant dependency ExprTools

docs/Project.toml
=> Allow JLD2 v0.6 in docs

Project.toml
=> Allow IntervalMatrices v0.12
