docs/src/man/nonlinear.md
src/Algorithms/ASB07/post.jl
src/Algorithms/GLGM06/post.jl
src/Algorithms/GLGM06/reach.jl
src/Algorithms/TMJets/TMJets.jl
src/Flowpipes/flowpipes.jl
src/Flowpipes/reachsets.jl
src/Flowpipes/solutions.jl

- fix order reduction to use internal method (type stable)
-  let `project(sol, vars=(i, j))` also work, as it matches `plot(sol, vars=(i, j))`
- fix setrep to work on types
- decrease default absolute tolerance in TMJets to 1e-15
- add example (Lotka-Volterra) in the Nonlinear section

Various fixes

---

src/Algorithms/ASB07/ASB07.jl
src/Algorithms/ASB07/post.jl
src/Algorithms/BFFPSV18/BFFPSV18.jl
src/Algorithms/BOX/BOX.jl
src/Algorithms/BOX/post.jl
src/Algorithms/BOX/reach_homog.jl
src/Algorithms/GLGM06/GLGM06.jl
src/Algorithms/GLGM06/post.jl
src/Algorithms/GLGM06/reach_inhomog.jl
src/Algorithms/INT/INT.jl
src/Algorithms/INT/reach_homog.jl
src/Algorithms/LGG09/LGG09.jl
src/Continuous/discretization.jl
src/Continuous/exponentiation.jl
src/Continuous/normalization.jl
src/Flowpipes/setops.jl
test/algorithms/ASB07.jl
test/algorithms/BOX.jl
test/algorithms/GLGM06.jl
test/solve.jl

Breaking changes:
- we now set `recursive=true` for ASB07
- `static=true` is (temporarily) disabled for GLGM06
In general the purpose of this PR is bringing type parameters for those options that define the behavior  of the program, ie. for cases where we want to do dispatch on such parameters. So from the user API we still instantiate with values, like `ASB07(recursive=true)`, but internally this is compiled to an `ASB07` instance with the `alg.recursive == Val{true}` value type, so for intermediate computations we can dispatch on that option without losing inference.

Add value type parameters

---

src/Algorithms/GLGM06/post.jl
src/Continuous/solve.jl
src/Hybrid/time_triggered.jl

Closes #68.
- `_promote_tspan` returns a `TimeInterval` (in the future we may add a time parameter to that type, such that it's of the form `IA.Interva{N}`)
- the case where the time span is defined a posteriori is solved by using `IntervalArithmetic.emptyinterval()` (which is also an interval, so the function is type-stable)
- dispatch on `solve` directly for systems with clocked linear dynamics

Cleanup tspan conversions

---

docs/src/man/hybrid.md
docs/src/references.md
src/Algorithms/ASB07/ASB07.jl
src/Algorithms/ASB07/post.jl
src/Algorithms/BOX/BOX.jl
src/Algorithms/GLGM06/GLGM06.jl
src/Flowpipes/flowpipes.jl
src/Flowpipes/setops.jl
src/Hybrid/time_triggered.jl
src/Initialization/exports.jl
test/algorithms/ASB07.jl
test/models/hybrid/embrake.jl
test/runtests.jl
test/solve.jl

Closes https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/7.
Closes https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/131.

Generalize jitter in clocked systems

---

docs/src/man/hybrid.md
docs/src/references.md
src/Algorithms/ASB07/ASB07.jl
src/Algorithms/ASB07/post.jl
src/Algorithms/BOX/BOX.jl
src/Algorithms/GLGM06/GLGM06.jl
src/Flowpipes/flowpipes.jl
src/Flowpipes/recipes.jl
src/Flowpipes/setops.jl
src/Hybrid/time_triggered.jl
src/Initialization/exports.jl
test/algorithms/ASB07.jl
test/models/hybrid/embrake.jl
test/runtests.jl
test/solve.jl

This PR is based on https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/134.
The purpose is to reduce allocations by lazily shifting the flowpipe along the time direction.
Some care should be taken when using `ShiftedFlowpipe`, because `tspan(F[i])` uses the incorrect method (at it can't dispatch on `typeof(F)`); we should use `tspan(F, i)` instead.
For BOX algorithm and statically sized arrays this gives my machine ~10x speedup with respect to `master`:
```julia
using Plots, BenchmarkTools
using Revise, ReachabilityAnalysis
include("/home/mforets/.julia/dev/ReachabilityAnalysis/test/models/hybrid/embrake.jl")
LazySets.deactivate_assertions()
prob = embrake_no_pv(ζ=0.0, Tsample=1e-4);
@time sol = solve(prob, alg=BOX(δ=1e-8, static=true, dim=4), max_jumps=1000);
@time sol = …
```

Lazily shift flowpipes in time triggered problems

---

src/Flowpipes/setops.jl

```julia
julia> Z = Zonotope(rand(4), rand(4, 8) .- 0.5);
julia> Zst = Zonotope(SVector{4}(Z.center), SMatrix{4, 8}(Z.generators));
julia> @btime ReachabilityAnalysis._reduce_order($Z, 1); # master
525.942 ns (19 allocations: 1.50 KiB)
julia> @btime ReachabilityAnalysis._reduce_order($Zst, 1);  # master
418.739 ns (11 allocations: 1.20 KiB)
julia> @btime ReachabilityAnalysis._reduce_order($Z, 1);   # new
321.116 ns (8 allocations: 624 bytes)
julia> @btime ReachabilityAnalysis._reduce_order($Zst, 1); # new
273.169 ns (7 allocations: 560 bytes)
```

Refactor + small improvements in order reduction functions

---

src/Algorithms/TMJets/TMJets.jl
src/Algorithms/TMJets/post.jl
src/Algorithms/TMJets/reach.jl
src/Algorithms/TMJets/validated_integ.jl

This PR the TMJets algorithm to refine the `abs_tol` automatically whenever the validation step (`remainder_taylorstep!`) fails. It allows solving relatively quickly those cases that would require a very small tolerance only for some part of the flowpipe.
In this proof of principle we monotonically decrease the abs_tol -- it just iterates calls to `validated_integ!`  with the last set from the previous flowpipe, adjusting the start time. Seems to me that working in the inner functions themselves gives a computational advantage, but i would leave that for later.
In the case of the Michaelis-Menten problem, for instance,  printing the abs_tol refinements gives:
```julia
start time t0 = 15.198728314843022, abs_tol = 1.0e-10
start time t0 = 53.384765311895436, abs_tol = 1.0000000000000001e-11 …
```

Add adaptive abs_tol option for TMJets

---

src/Flowpipes/reachsets.jl

xref: https://github.com/JuliaIntervals/TaylorModels.jl/pull/74

Use exact tdom in overapproximation of Taylor models

---

src/Flowpipes/flowpipes.jl
src/Initialization/exports.jl
test/hybrid.jl

With this PR, the function `location` can now be applied to flowpipes to retrieve the location associated to the flowpipe.

Add location getter for flowpipes

---

src/Flowpipes/setops.jl
src/Initialization/exports.jl
test/runtests.jl
test/setops.jl

This method allows to evaluate X ∩ Y approximately using support function calls, using that the support function of X ∩ Y along direction d satisfies ρ(d, X ∩ Y) <= min(ρ(d, X), ρ(d, Y)). The template is a parameter of the type; if it's missing then we use the directions normal to X and Y.

Add TemplateHullIntersection

---

src/Continuous/discretization.jl
src/Initialization/exports.jl
test/algorithms/GLGM06.jl

Add NoBloating  approximation model

---

src/Hybrid/transitions.jl
test/hybrid.jl

This method lets one use the `TemplateHullIntersection` method in discrete transitions. For the time being i just added the `apply` dispatch were all sets are polyhedral. (Note that `X` should also be annotated as polyhedral for the case of the `LGG09` algorithm which can partially compute the flowpipe).
In a comment i described the choice of the order of the operations for this implementation, which performs 1 concrete intersectin with HRep and 2 template intersections. There are certainly other ways of making this operation. In fact, Frehse & Ray's paper offer anther method which does only one template hull operation. We can do this in a follow up PR.
```julia
using Revise, ReachabilityAnalysis, Plots
const RA = ReachabilityAnalysis …
```

Add (generic) template hull intersection for discrete transitions'

---

src/Algorithms/TMJets/TMJets.jl
src/Continuous/solve.jl
test/algorithms/TMJets.jl

Let TMJets options be passed outside the struct

---

.gitignore
docs/Project.toml
docs/generate.jl
docs/make.jl
test/models/nonlinear/vanderpol.jl

This is a first proposal for adding the models to the documentation in Literate style.
One central issue is that the models are used in the tests and hence need functions to return the problem. But in the documentation such a function is causing problems when plotting. As a compromise I hide the `function model_name() [...] end` frame in the documentation, but the four leading spaces are still there.

Add Van-der-Pol model to documentation

---

src/Flowpipes/clustering.jl

Generalize cluster functions for AbstractLazyReachSet.
Closes #226.

issue #226 - generalize cluster functions for AbstractLazyReachSet

---

src/Flowpipes/flowpipes.jl

The assumptions that the time spans are contiguous in HybridFlowipes breaks as long as we use clustering with more than 1 output set. This PR changes that assumption so `tspan` works correctly in general. OTOH the evaluation interface still needs to be generalized, i left this for later.

Fix tspan for hybrid flowpipes

---

src/Algorithms/TMJets/post.jl

With this PR we can call TMJets with an external solver from TaylorModels using the `external=true` flag. Pass a `solver_name` to specify using a function different than `validated_integ`.
cc: @UzielLinares

External kwarg to TMJets solver

---

Project.toml
src/Algorithms/GLGM06/reach_homog.jl
src/Algorithms/GLGM06/reach_inhomog.jl
src/Continuous/discretization.jl
src/Flowpipes/setops.jl
src/Initialization/init.jl

The internal functions `_linear_map`, `_linear_map!` and `_scale!` are no longer needed because the patches are now available in LazySets.

Remove inner linear_map function

---

Project.toml
docs/make.jl
docs/src/lib/internals.md
docs/src/lib/operations.md
src/Flowpipes/setops.jl
src/Initialization/init.jl

This macro is useful to annotate functions that are commutative with respect to its first two arguments, automatically creating `foo(Y, X)` given `foo(X, Y)`. 
(This method is from LazySets PR https://github.com/JuliaReach/LazySets.jl/pull/2286 but it is not available in that package yet.)

Macro for commutative binary functions

---

Project.toml
src/Continuous/normalization.jl
src/Continuous/solve.jl
src/Flowpipes/fields.jl
src/Flowpipes/solutions.jl
src/Initialization/exports.jl
src/Initialization/init.jl
src/Initialization/init_DifferentialEquations.jl

```julia
@time using ReachabilityAnalysis, DifferentialEquations
using Plots
using ReachabilityAnalysis: solve
┌ Info: Precompiling ReachabilityAnalysis [1e97bd63-91d1-579d-8e8d-501d2b57c93f]
└ @ Base loading.jl:1278
50.864150 seconds (86.59 M allocations: 4.762 GiB, 2.69% gc time)
WARNING: using DifferentialEquations.solve in module ReachabilityAnalysis conflicts with an existing identifier.
prob = @ivp(x' = 1.01x, x(0) ∈ 0 .. 0.5);
@time sol = solve(prob, tspan=(0.0, 1.0));
@time sol = solve(prob, tspan=(0.0, 1.0), ensemble=false);
@time sol = solve(prob, tspan=(0.0, 1.0), ensemble=true);
0.000028 seconds (627 allocations: 14.516 KiB)
0.000045 seconds (627 allocations: 14.516 KiB)
0.002557 seconds (12.66 k allocations: 1.287 MiB)
plot(sol, vars=(0, 1))
plot!(ensemble(sol), vars=(0, 1)) …
```

Update ensemble solver

---

src/Flowpipes/clustering.jl

Closes https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/347
@dfcaporale  if you have time to try again the model that triggered https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/347 and check that it is now fixed (or not) that would be great! iirc this method makes sense only if we set `UnionSetArray <: LazySet`  (that's why i didn't add a test here).

update cluster method with unions

---

src/Flowpipes/reachsets.jl
src/Flowpipes/setops.jl

Now available in LazySets (https://github.com/JuliaReach/LazySets.jl/pull/2469) we can remove the patch.

update concrete complement

---

docs/generate.jl
docs/make.jl
docs/src/references.md
examples/ISS/ISS.jl
src/Flowpipes/recipes.jl
test/models/ISS.jl
test/models/Platoon.jl

This PR extends the logic in `_project_reachset(R::TemplateReachSet, vars)` such that the "fast" and exact AbstractPolyhedron projection method from LazySets is used if it is applicable, otherwise we overapproximate the lazy projection.

Extend projection recipe for template reach-sets

---

src/Algorithms/TMJets/TMJets21a/post.jl
src/Algorithms/TMJets/TMJets21b/post.jl
src/Algorithms/TMJets/common.jl

This restores the usual behavior (do not return the set of initial states, only the propagated states).

Changes to skip first set

---

src/Flowpipes/recipes.jl

x-ref: #453
Here are the numbers of generators before and after removing when plotting a flowpipe for some model (`Airplane`). This is an 18-dimensional model, so removing generators helps a lot.
```
25
3
25
3
25
3
25
3
25
3
25
3
25
3
25
2
25
2
25
2
25
2
25
2
31
3
31
3
31
3
31
4
31
4
31
3
31
3
31
2
31
2
31
2
31
2
31
2
31
2
31
2
```

Remove redundant generators when plotting zonotopes

---

src/Discretization/ForwardDdt.jl
src/Discretization/discretization.jl
test/algorithms/LGG09.jl

~This requires https://github.com/JuliaReach/LazySets.jl/pull/2800.~
```julia
using ReachabilityAnalysis, Plots
using ReachabilityAnalysis: ForwardDdt
import DifferentialEquations
A = [0.0 1.0; -1.0 0.0]
X0 = BallInf([1.0, 1.0], 0.1)
prob = @ivp(x' = Ax, x(0) ∈ X0)
dt = (0.0, 20.0)
δ = 2e-1
X1 = linear_map(exp(A*δ), X0)
template = PolarDirections(200)
sol = solve(prob, ensemble=true, include_vertices=true, trajectories=0, tspan=dt, alg=LGG09(δ=δ, template=template, approx_model=ForwardDdt()));
sol_ua = solve(prob, tspan=dt, alg=LGG09(δ=δ, template=template, approx_model=ForwardDdt(oa=false)));
plot(X0)
plot!(X1)
plot!(sol[1], vars=(1, 2), alpha=0.2)
plot!(convex_hull(X0, X1), alpha=0.2)
plot!(sol_ua[1], vars=(1, 2), alpha=0.5)
plot!(ensemble(sol), vars=(1, 2), alpha=1, c=:black) …
```

Add discretization method from d/dt

---

Project.toml
src/Hybrid/solve.jl
src/Initialization/init_DifferentialEquations.jl
test/hybrid.jl
test/models/hybrid/thermostat.jl
test/runtests.jl

~This PR is based on #539.~
Possible future additions:
* urgent transitions
* interpolation between time steps (currently we need to enforce a small time step for reasonable results)
```julia
using ReachabilityAnalysis
using HybridSystems, MathematicalSystems, LazySets, LinearAlgebra
using LazySets: HalfSpace  # resolve name-space conflicts with Polyhedra
function thermostat()
c_a = 0.1
automaton = LightAutomaton(2)
A = hcat(c_a)
inv = HalfSpace([1.0], 22.0)  # x ≤ 22
m_on = ConstrainedLinearContinuousSystem(A, inv)
A = hcat(-c_a)
inv = HalfSpace([-1.0], -18.0)  # x ≥ 18
m_off = ConstrainedLinearContinuousSystem(A, inv)
modes = [m_on, m_off]
add_transition!(automaton, 1, 2, 1)
guard = HalfSpace([-1.0], -21.0)  # x ≥ 21
t_on2off = ConstrainedIdentityMap(2, guard)
add_transition!(automaton, …
```

Simulation for hybrid systems

---

src/Hybrid/transitions.jl

I restarted the docs build 3 times. It fails precompiling `Plots`. This PR is safe to merge.

Fix transition method

---

docs/Project.toml
docs/src/tutorials/set_representations/zonotopes.md
test/models/LotkaVolterra.jl

The first commit has a change that was automatically applied when I built the docs.
For the second commit, I got the following errors:
```julia
┌ Warning: failed to run `@example` block in src/tutorials/set_representations/zonotopes.md:32-36
│ ```@example zonotope_definition
│ @show center(Z)
│ 
│ @show genmat(Z)
│ ```
│   c.value = UndefVarError: center not defined
└ @ Documenter.Expanders ~/.julia/packages/Documenter/qdbx6/src/Expanders.jl:591
┌ Warning: failed to run `@example` block in src/tutorials/set_representations/zonotopes.md:40-42
│ ```@example
│ Z3 = Zonotope([1.0, 0.0], [0.1 0.0; 0.0 0.1])
│ ```
│   c.value = UndefVarError: Zonotope not defined
└ @ Documenter.Expanders ~/.julia/packages/Documenter/qdbx6/src/Expanders.jl:591
┌ Warning: failed to run `@example` block in …
```

Fix docs problem

---

Project.toml
src/ReachSets/TaylorModelReachSet.jl

This fixes a bug introduced in #603: The time point has to be converted to an interval before intersecting with another interval.

Fix overapproximate(::TMRS, ::Zonotope, ::AbstractFloat)

---

src/ReachSets/TaylorModelReachSet.jl

`symBox(R)` is not defined. Apparently there is no test for this method.

Fix overapproximate(::TMRS, Hyperrectangle)

---

Project.toml
src/Continuous/normalization.jl
test/runtests.jl

This supersedes #658.
I also suggested a new minor release because `MathematicalSystems` is reexported, so dependencies of this package may break.

Support new version of MathematicalSystems

---

docs/src/man/hybrid.md
src/Discretization/discretization.jl

There is an error when using `GLGM06` with hybrid systems because we do not allow to *not* intersect with the source invariant anymore (`nothing` is not a valid parameter anymore because of the restriction to `AbstractIntersectionMethod`) 
https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/1456c3965df8ef37164cdc022f8d3880d883f37e/src/Hybrid/solve.jl#L12
https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/1456c3965df8ef37164cdc022f8d3880d883f37e/src/Hybrid/solve.jl#L25-L27
This means that the `else` branch below is effectively dead code:
https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/1456c3965df8ef37164cdc022f8d3880d883f37e/src/Hybrid/solve.jl#L251-L256
That lead to the bouncing ball failing because `X0` is converted to an `HPolytope`, which the discretization …

Fix bouncing-ball example

---

Project.toml
src/Discretization/exponentiation.jl
src/Initialization/init.jl
src/Initialization/init_Expokit.jl
test/discretization.jl
test/runtests.jl

In `master`:
```julia
julia> using ReachabilityAnalysis, SparseArrays
julia> using ReachabilityAnalysis: _exp, PadeExpAlg
julia> A = sparse([10.0 0; 0 20]); δ = 0.1;
julia> _exp(A, δ, PadeExpAlg())
ERROR: AssertionError: package `Expokit` is required for this function; do `using Expokit` and try again
julia> using Expokit
julia> _exp(A, δ, PadeExpAlg())
ERROR: AssertionError: package `Expokit` is required for this function; do `using Expokit` and try again
```

Fix Pade approximation and test _exp

---

src/ReachSets/TaylorModelReachSet.jl
test/reachsets/reachsets.jl

1. The methods
```julia
function _overapproximate(R::TaylorModelReachSet{N}, ::Type{<:Hyperrectangle};
Δt::TimeInterval=tspan(R), dom=symBox(dim(R))) where {N}
function _overapproximate(R::TaylorModelReachSet{N}, ::Type{<:Zonotope};
Δt::TimeInterval=tspan(R), dom=symBox(dim(R))) where {N}
```
only differed in the last line (modulo reordering of other lines).
2. The method
```julia
function overapproximate(R::TaylorModelReachSet{N}, ::Type{<:Zonotope}, t::AbstractFloat;
remove_zero_generators=true) where {N}
```
was almost identical too; now it calls the common method above instead. Furthermore, a method for time points and `Hyperrectangle` was not available; now it is.
3. I added a TODO to outsource some code to `LazySets`. I already added a PR for that here: …

Merge code for overapproximate of TaylorModelReachSet

---

Project.toml
src/ReachSets/TaylorModelReachSet.jl

This fixes an error introduced in #766 where the wrong method was called.

Fix overapproximate method; v0.23.1

---

docs/generate.jl
examples/Brusselator/Brusselator.jl
examples/Building/Building.jl
examples/DuffingOscillator/DuffingOscillator.jl
examples/EMBrake/EMBrake.jl
examples/Heat3D/Heat3D.jl
examples/ISS/ISS.jl
examples/LaubLoomis/LaubLoomis.jl
examples/Lorenz/Lorenz.jl
examples/LotkaVolterra/LotkaVolterra.jl
examples/LotkaVolterraTangential/LotkaVolterraTangential
examples/OpAmp/OpAmp.jl
examples/Platoon/Platoon.jl
examples/ProductionDestruction/ProductionDestruction.jl
examples/Quadrotor/Quadrotor.jl
examples/SEIR/SEIR.jl
examples/Spacecraft/Spacecraft.jl
examples/SquareWaveOscillator/SquareWaveOscillator.jl
examples/TransmissionLine/TransmissionLine.jl
examples/VanDerPol/VanDerPol.jl

Build time with notebooks: 12m 9s
Build time without notebooks: 7m 48s

Revise Literate script and deactivate notebook generation

---

docs/src/lib/reachsets.md
src/Flowpipes/Flowpipe.jl
src/Flowpipes/MappedFlowpipe.jl
src/Flowpipes/ShiftedFlowpipe.jl
src/Flowpipes/clustering.jl
src/Flowpipes/recipes.jl
src/Flowpipes/setops.jl
src/Hybrid/solve.jl
src/Hybrid/waiting_list.jl
src/ReachSets/AbstractLazyReachSet.jl
src/ReachSets/ReachSet.jl
src/ReachSets/TaylorModelReachSet.jl
test/Aqua.jl

Fix unbound args

---

src/Flowpipes/AbstractFlowpipe.jl
src/ReachSets/AbstractReachSet.jl

An alternative would be to let `LazySets` define `box_approximation` without type restrictions.
EDIT: `LazySets` actually defines it the other way around:
`overapproximate(S::LazySet, ::Type{<:Hyperrectangle}) = box_approximation(S)`
Nevertheless, the point remains.
If not, we should probably still use the same convention here and rename all methods to `box_approximation` (and then add an alias with `overapproximate`).

Define `box_approximation` for `AbstractReachSet`s and `AbstractFlowpipe`s

---

src/Initialization/init.jl

`flatten` was added to `LazySets` but we did not import it here. Thus usages outside the library crash.
```
WARNING: both LazySets and ReachabilityAnalysis export "flatten"; uses of it in module Main must be qualified
```

Import `flatten`

---

examples/Spacecraft/Spacecraft.jl

The settings used in ARCH-COMP2020 did not use the larger target box yet. Since other changes were introduced before this change, it is more consistent to go back to the small target box.
As an alternative, [#815](https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/815) adds the newer settings.

Adapt Spacecraft settings to ARCH-COMP2020

---

docs/src/tutorials/linear_methods/discrete_time.md
src/Flowpipes/setops.jl

See #788. Four ambiguities remain.
EDIT: The first commits have been outsourced to #811 and merged. This branch is now rebased.
~~The first commit makes changes that should be clear.~~
The other commits change/remove behaviors. But I would argue that we do not need these anymore now that unions are `LazySet`s, and some methods have been questionable.

Fix ambiguities

---

Project.toml
src/Flowpipes/setops.jl

This fixes some piracies (see #790).
Again the docs build does not see the latest LazySets release, while the test build sees it. I think I now understand why this happens - I had the same problem when doing `dev ..` from the `docs/` project. In any case, I ran the docs build locally and it passed.

Outsource code to LazySets

---

docs/src/lib/flowpipes.md
docs/src/lib/internals.md
docs/src/lib/reachsets.md
src/Flowpipes/AbstractFlowpipe.jl
src/ReachSets/AbstractReachSet.jl
test/flowpipes/flowpipes.jl

The function was actually never used.

Remove `basetype` (available in ReachabilityBase)

---

src/Flowpipes/Flowpipe.jl
src/Flowpipes/clustering.jl
test/Aqua.jl
test/flowpipes/flowpipes.jl

Remove confusing membership method

---

src/Discretization/Overapproximate.jl

The implementation was not specific to `Hyperrectangle`s at all, so I generalized it.

Merge and generalize `overapproximate` methods with `HPolytope`

---

src/Algorithms/GLGM06/post.jl
test/algorithms/GLGM06.jl

This is an example how to add discrete post functions for the linear algorithms. 
`solve` is not implemented yet.
```julia
function exponential_1d(; invariant=Universe(1))
s = @system(x' = -x, x ∈ invariant)
x0 = Interval(0.4, 0.5)
prob = InitialValueProblem(s, x0)
tspan = (0.0, 1.0)
return prob, tspan
end
ivp, _ = exponential_1d()
alg = GLGM06(; δ=0.01)
sol_c = solve(ivp; T=5.0, alg=alg);
ivp_norm = ReachabilityAnalysis._normalize(ivp)
ivp_discr = discretize(ivp_norm, alg.δ, alg.approx_model)
NSTEPS = 500
fp_d = ReachabilityAnalysis.post(alg, ivp_discr, NSTEPS);
```
At the end, `flowpipe(sol_c) == fp_d` would hold, but `==` is not defined for flowpipes.

Add discrete post for `GLGM06`

---

src/Algorithms/A20/post.jl
src/Algorithms/ASB07/post.jl
src/Algorithms/BFFPSV18/post.jl
src/Algorithms/BOX/post.jl
src/Algorithms/GLGM06/post.jl
src/Algorithms/INT/post.jl
src/Algorithms/LGG09/post.jl
src/Algorithms/VREP/post.jl
test/algorithms/ASB07.jl
test/algorithms/BOX.jl
test/algorithms/GLGM06.jl
test/algorithms/INT.jl
test/algorithms/LGG09.jl
test/algorithms/VREP.jl

Follow-up of #861 with analogous changes.

Add discrete post for linear algorithms

---

src/Initialization/init_OrdinaryDiffEq.jl

```julia
┌ Warning: `Base.getindex(A::AbstractVectorOfArray, I::Int)` is deprecated, use `Base.getindex(A, :, I)` instead.
```

Fix deprecation warning in OrdinaryDiffEq

---

test/Project.toml

Allow Polyhedra v0.8 and CDDLib v0.10 in tests

---

docs/src/lib/systems.md
docs/src/man/systems.md
src/Continuous/homogenization.jl
src/ReachabilityAnalysis.jl
test/algorithms/BOX.jl

The function `homogenize` was not tested and actually did not work.

Fix `homogenize`

---

src/Continuous/normalization.jl
test/algorithms/BOX.jl

This fixes an issue uncovered in #889.
The proposed change assumes that `scale` is available for the input set. This currently holds at least for the common input sets (`Singleton`, `Hyperrectangle`, `Zonotope`).

Use `scale` for linear map with `IdentityMultiple`
